# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_addr', models.CharField(max_length=250)),
                ('dropoff_addr', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('pickup_time', models.DateTimeField()),
                ('dropoff_time', models.DateTimeField()),
                ('items', models.IntegerField(choices=[(0, 'Food'), (1, 'Electironics'), (2, 'Leather'), (3, 'Machinery'), (4, 'Utility'), (5, 'Household')])),
                ('payment_type', models.IntegerField(choices=[(0, 'COD'), (1, 'Pre-paid')])),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
