# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Started'), (1, 'Published'), (2, 'Finished')], default=0),
        ),
    ]
