# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20160421_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.IntegerField(choices=[(0, 'Food'), (1, 'Electironics'), (2, 'Leather'), (3, 'Machinery'), (4, 'Utility'), (5, 'Household')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_addr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
