# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20160507_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dropoff_addr',
            field=models.CharField(default='ottawa', max_length=250),
            preserve_default=False,
        ),
    ]
