# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20160507_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
