# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='address',
            field=models.CharField(default='victoria', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sender',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sender',
            name='package_type',
            field=models.CharField(choices=[('Food', 'Food'), ('Electironics', 'Electironics'), ('Leather', 'Leather'), ('Machinery', 'Machinery'), ('Utility', 'Utility'), ('Household', 'Household')], default='Food', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sender',
            name='phone',
            field=models.CharField(default='60173160084', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sender',
            name='store_url',
            field=models.CharField(default='shoppingmall.com', max_length=50),
            preserve_default=False,
        ),
    ]
