# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_addr', models.CharField(max_length=250)),
                ('dropoff_addr', models.CharField(max_length=250)),
                ('contact_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('pickup_time', models.DateTimeField()),
                ('dropoff_time', models.DateTimeField(blank=True, null=True)),
                ('items', models.CharField(choices=[('Food', 'Food'), ('Electironics', 'Electironics'), ('Leather', 'Leather'), ('Machinery', 'Machinery'), ('Utility', 'Utility'), ('Household', 'Household')], max_length=50)),
                ('payment_type', models.CharField(choices=[('COD', 'COD'), ('Pre-paid', 'Pre-paid')], max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Initial', 'Initial'), ('Received', 'Received'), ('Finished', 'Finished')], default='Initial', max_length=20)),
                ('track_link', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
