# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dropoff_time',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
