# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20160501_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Received', 'Received'), ('Finished', 'Finished')], default='Initial', max_length=20),
        ),
    ]
