# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20160507_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.CharField(choices=[('Food', 'Food'), ('Electironics', 'Electironics'), ('Leather', 'Leather'), ('Machinery', 'Machinery'), ('Utility', 'Utility'), ('Household', 'Household')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'COD'), ('Pre-paid', 'Pre-paid')], max_length=50),
        ),
    ]
